export enum PortfolioTags {
  "ANGULAR" = "Angular",
  "ANGULARJS" = "AngularJS (1.0)",
  "REACTJS" = "ReactJS",
  "NEXTJS" = "NextJS",
  "PHP" = "PHP",
  "WORDPRESS" = "WordPress",
  "UBUNTU" = "Ubuntu",
  "FIREBASE" = "FireBase",
  "NOSQL" = "NoSQL",
  "RUBYONRAILS" = "Ruby on Rails",
  "IONIC" = "Ionic",
  "CORDOVA" = "Cordova",
  "PUBLISHING" = "Publishing",
  "ADSENSE" = "AdSense",
  "MAGENTO" = "Magento (1.0)",
  "CICD" = "CI / CD",
  "TAILWINDCSS" = "Tailwind CSS",
  "STENCILJS" = "StencilJS",
}
